# 3.1 텐서와 Autograd

##3.1.1 텐서 차원 다루기

In [1]:
import torch

In [2]:
# 램크 2 텐서 (x,y, 2차원이기때문)
x= torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [3]:
# 사이즈, 쉐입, 차원 확인하는 방법
print("Size: ", x.size())
print("Shape: ", x.shape)
print("랭크:", x.ndimension())

Size:  torch.Size([3, 3])
Shape:  torch.Size([3, 3])
랭크: 2


In [4]:
# 랭크 늘리기-> 차원을 늘리는것
x = torch.unsqueeze(x, 0)
print(x)
print("Size: ", x.size())
print("Shape: ", x.shape)
print("랭크:", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size:  torch.Size([1, 3, 3])
Shape:  torch.Size([1, 3, 3])
랭크: 3


In [5]:
# 랭크 줄이기-> 차원을 줄이는것
x = torch.squeeze(x)
print(x)
print("Shape:", x.shape)
print("Shape: ", x.shape)
print("랭크:", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])
Shape:  torch.Size([3, 3])
랭크: 2


In [8]:
# 텐서의 모양을 바꾸는 방법_  텐서의 모양이 바뀌면서 1랭크로 변함
x = x.view(9)
print(x)
print("Shape:", x.shape)
print("Shape: ", x.shape)
print("랭크:", x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Shape: torch.Size([9])
Shape:  torch.Size([9])
랭크: 1
