# 3.1 텐서와 Autograd

##3.1.1 텐서 차원 다루기

In [1]:
import torch

In [2]:
# 램크 2 텐서 (x,y, 2차원이기때문)
x= torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [3]:
# 사이즈, 쉐입, 차원 확인하는 방법
print("Size: ", x.size())
print("Shape: ", x.shape)
print("랭크:", x.ndimension())

Size:  torch.Size([3, 3])
Shape:  torch.Size([3, 3])
랭크: 2


In [4]:
# 랭크 늘리기-> 차원을 늘리는것
x = torch.unsqueeze(x, 0)
print(x)
print("Size: ", x.size())
print("Shape: ", x.shape)
print("랭크:", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size:  torch.Size([1, 3, 3])
Shape:  torch.Size([1, 3, 3])
랭크: 3


In [5]:
# 랭크 줄이기-> 차원을 줄이는것
x = torch.squeeze(x)
print(x)
print("Shape:", x.shape)
print("Shape: ", x.shape)
print("랭크:", x.ndimension())

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])
Shape:  torch.Size([3, 3])
랭크: 2


In [8]:
# 텐서의 모양을 바꾸는 방법_  텐서의 모양이 바뀌면서 1랭크로 변함
x = x.view(9)
print(x)
print("Shape:", x.shape)
print("Shape: ", x.shape)
print("랭크:", x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Shape: torch.Size([9])
Shape:  torch.Size([9])
랭크: 1


###3.1.2 연산과 행렬곱

In [9]:
# 일반 수학에서의 행렬곱과 같다고 보면된다

In [18]:
# 행렬정의
a = torch.randn(5,3, dtype = torch.float)
b = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

print("a size:", a.size())
print("b size:", b.size())
print(a)
print(b)

a size: torch.Size([5, 3])
b size: torch.Size([3, 2])


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [20]:
# 연산에 쓰일 행렬 추가
c = torch.randn(5,2, dtype = torch.float)
c

tensor([[ 0.2371, -0.6799],
        [ 0.9994, -1.5136],
        [ 1.2248, -0.5345],
        [ 1.8143,  0.1355],
        [-0.8643, -1.7029]])

In [22]:
# 행렬 곱 방법 torch.mm 사용
ab = torch.mm(a,b)
print("ab size:", ab.size())
print(ab)

ab size: torch.Size([5, 2])
tensor([[ 0.2631,  1.3526],
        [-0.8155, -2.2326],
        [-7.9376, -9.8929],
        [ 3.2135,  5.4229],
        [11.0425, 14.5151]])


#### 3.1.3  Autograd

##### 경사 하강법을 이용하여 오차를 줄여나가는 기울기를 찾으며 이를 위해서 autograd를 배운다. 
##### = 미분 계산을 자동화하여 경사하강법 구현을 편리하게 해줌

In [35]:
a = torch.tensor(1.0, requires_grad = True) # Ture로 할시 a.grad에 미분값이 자동으로 저장된다.
print(a.grad)

None


In [36]:
b = a*3

In [37]:
c = b**2

In [38]:
# c = b^2 = (a*3)^2 = 9a^2

In [39]:
# 미분해주는 함수: backward()
c.backward()
print('c를 a로 미분 한 값은 {}'.format(a.grad))

c를 a로 미분 한 값은 18.0
